# Generated by Django 5.2.7 on 2025-11-14 04:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_set_email_jona'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='passwordresetcode',
            new_name='accounts_pa_email_e9c446_idx',
            old_name='accounts_pa_email_c_0d7a22_idx',
        ),
        migrations.RenameIndex(
            model_name='passwordresetcode',
            new_name='accounts_pa_expires_d44861_idx',
            old_name='accounts_pa_expires_6f4e2d_idx',
        ),
    ]
