# Generated by Django 5.2.6 on 2025-11-24 18:07

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('type', models.CharField(choices=[('factura_venta', 'Factura de venta'), ('nota', 'Nota')], db_index=True, max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('invoice_sale', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='calendar_entries', to='invoices.facturaventa')),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
